### ISSUE TITLE
favourites recipes

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#1]
​
## Value Proposition
​
**As a** user
**I want to** see my choosen favourite recipes
**so that I** keep them in my mind.

​
## Description

![Image](https://user-images.githubusercontent.com/112656434/201956198-4d447298-869e-4099-bcd1-396a76e1682c.png)

​
## Acceptance Criteria
​
- Recipes are displayed as cards in a list on the page 
- the headline is "WTF? What to food"
- the subline is "my super tasty selection of recipes:"
- the cards include a placeholder image

​
## Tasks
​
- [x] create a feature branch
- [x] create a `FoodCard` component 
- [x] add placeholder image
- [x] add headline "WTF? - What to food?" to `MealCenter` page
- [x] add subline "my super tasty selection of recipes:"
- [x] create dummy data array
- [x] display dummy data array in `MealCenter` page

## Complexicity

M
