### ISSUE TITLE
add comment

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#12]
## Value Proposition
​
**As a** user
**I want to** add comments to my favourite recipes
**so that I can** add my own opinion, ideas and tips on how to prepare this recipe.
​
## Description

![Image](https://user-images.githubusercontent.com/112656434/205498840-0cc4f2af-a100-40a6-8198-87ab6e101598.png)

​
## Acceptance Criteria
​
- clicking on the comment button on the recipe `detailpage` open a textfield to write a comment
- 
- After saving the comment is shown on the recipe.
​
## Tasks
​
- [x] create a feature branch
- [x] create a button at the FoodCard Component
- [x] create a form / input
- [x] link this form with the button at FoodCard component 
- [x] create a function to show the saved the comments to the FoodCard. 

## Complexicity

M
