### ISSUE TITLE
whos choice

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#13]
## Value Proposition
​
**As a** user
**I want to** see which member of my family add the recipes to the favourites.
**so that I can** decide what is cooked depending on who eats with me.
​
## Description

![Image](https://user-images.githubusercontent.com/112656434/205499401-8b9a40d5-2918-46cb-9df7-ba0ab03d4117.png)

​
## Acceptance Criteria
​
- in the `MealCenter` a image shows who put the recipe to the favourites 

​
## Tasks
​
- [x] create a feature branch
- [x] create a array with fake data for family members
- [x] display the array at my foodcard component.

## Complexicity

M
