### ISSUE TITLE
Choose recipes

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#2]
## Value Proposition
​
**As a** user
**I want to** be able to bookmark recipes
**so that I** have them saved and can cook them later on.

​
## Description

![Image](https://user-images.githubusercontent.com/112656434/202147997-64c70504-6d77-4944-a42b-4b37b7b62f52.png)

​
## Acceptance Criteria
​
- Recipes are displayed on the `index` page
- the headline is "WTF? What to food"
- the subline is "what are you up for?"
- the card include the image from one recipe as a placeholder
- when the button called delicious is clicked the current recipe is bookmarked and displayed on the 
  `MealCenter` page and the next recipes render on `index` page
- after the button called disgusting is clicked the next recipes render on `index` page
- At the bottom of the page is a navigation to switch between the index page and MealCenter page.
- The page, where the user is currently on, is highlighted in the navigation

​
## Tasks
​
- [x] create a feature branch
- [x] create a card to display the placeholder image from the recipes  
- [x] create a button with the text "delicious"
- [x] create a button with the text "disgusting"
- [x] create a eventHandler function to bookmark the recipe on buttonclick
- [x] add a navbar with icon for the `index` and `MealCenter` page
- [x] add links to the navbar items
- [x] navbar item is highlighted when i´m on the page

## Complexicity

L

**Comment by kochch1337** [comment]
Fine for me
