### ISSUE TITLE
fetch data from API

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#3]
## Value Proposition
​
**As a** user
**I want to** have a wide range of recipes to choose from
**so that I** don’t get bored and discover more new flavours and yummy things.

​
## Description

![Image](https://user-images.githubusercontent.com/112656434/202147703-0585a4d9-5180-49db-ac5a-60f65dabdb28.png)

​
## Acceptance Criteria
​
- On the `index` page recipes from the “TheMealDB” API are displayed instead of the previously used dummy data.
- When there is an error while fetching the data from the API, an error message is shown to the user.
- While the data is loading, a loading animation is shown to the user.

​
## Tasks
​
- [ ] create a feature branch
- [ ] remove dummy data
- [ ] fetch data from "TheMealDB" API
- [ ] use the existing card component to display the recipes from the API

## Complexicity

M

**Comment by gaiisay** [comment]
I think this is fine, maybe think about not fetching one at a time but fetching multiple entries but only displaying one at a time so you don't have to fetch so much (because this might make the app feel slower).
