### ISSUE TITLE
delete function

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#5]
## Value Proposition
​
**As a** user
**I want to** be able to delete my recipes as well
**so that I** have no recipes in my list that I no longer want to have and keep my recipe list clean.

​
## Description

![Image](https://user-images.githubusercontent.com/112656434/204631110-d25c36c1-7057-4297-ae69-57695177ae3a.png)

​
## Acceptance Criteria
​
- on the `MealCenter` page is an "edit" button.
- after click the deleting button the recipe is no longer visible
​
## Tasks
​
- [x] create a feature branch
- [x] add a "delete" button with an icon as buttontext
- [x] create a delete function to delete the card from the local storage 

## Complexicity

S

**Comment by FelineHuhn** [comment]
Hey Hendrik, good job. 

In the AC's it should read "IS" an edit button, not was. And also it should't be called function in the AC's, thats more like a task, e.g. you could write: by clicking the edit button a closing button will appear on the recipe card. (But for that I have a question: will only have one recipe card the closing button or every recipe card? If only one, i don't understand why the edit button is on the bottom of all recipes and not on each card (like the wireframes show). 

In the Task you should also mention the delete button first, before you describe his function. And you could also mention, that the edit button has an edit icon as button text and the delete button a closing icon.

**Comment by marialitwa** [comment]
Hej Hendrik, looks nice! :) Only a minor suggestion.. Value Proposition: You could delete "as well", I don't think it's necessary. Also you could probably only write : "so that I can keep my recipe list clean." Makes it more on point , but up to you :) And a question: why are you using an edit icon in the right bottom corner and not a delete icon instead, when it's about deleting? :)
