### ISSUE TITLE
details page

### ISSUE THREAD

**Issue by HendrikNeuschulz** [HendrikNeuschulz/Capstone-Projekt#6]
## Value Proposition
​
**As a** user
**I want to** be able to see the details of the recipes I have selected
**so that I** can learn more about recipe and cook it

​
## Description

![Image](https://user-images.githubusercontent.com/112656434/204631418-a8502b83-2e11-4ade-993d-a49d45f1c113.png)

​
## Acceptance Criteria
​
- Clicking on the picture of the recipe opens the `detail` page 
- on the detail page you can find all the necessary details for the recipe (name, ingredients and preparation)
- A back button takes you back to the `mealcenter`
​
## Tasks
​
- [x] create a feature branch
- [x] create a `details` page 
- [x] add the required data from the API on the `details` page
- [x] add a function to show the details after clicking on the image
- [x] add a back button to return to the `mealcenter` page

## Complexicity

L

**Comment by EugenMoser** [comment]
very good. Just one small thing:
`I want tobe able to see the details of the recipes I have selected`
a space between "I want to" and "be"
